@extends('layouts.app')

@section('title', 'Body Panel Assessment')

@section('content')
<div class="container-fluid px-4">
    <!-- Progress Breadcrumb -->
    <div class="row mb-3">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="/inspection/visual" style="color: var(--primary-color);">Visual Inspection</a></li>
                    <li class="breadcrumb-item active" aria-current="page" style="color: var(--primary-color); font-weight: 600;">Body Panel Assessment</li>
                    <li class="breadcrumb-item text-muted">Interior Assessment</li>
                </ol>
            </nav>
        </div>
    </div>

    <!-- Header -->
    <div class="text-center mb-4">
        <h1 class="display-5 text-gradient mb-2">ALPHA Inspection</h1>
        <h2 class="h4">Body Panel Assessment</h2>
        <p class="text-muted">Click on vehicle panels or hover over form labels to highlight areas</p>
    </div>

    <div class="row">
        <!-- Vehicle Body Panels Visual Section -->
        <div class="col-lg-6 mb-4">
            <div class="card shadow-sm">
                <div class="card-header" style="background-color: var(--primary-color); color: white;">
                    <h5 class="mb-0">Vehicle Body Panels</h5>
                </div>
                <div class="card-body">
                    <div class="body-panel-wrapper">
                        <div class="body-panel-container">
                            <!-- Base body panel image -->
                            <img src="/images/panels/FullVehicle.png" alt="Vehicle Base" class="base-body-panel" id="baseBodyPanel">
                            
                            <!-- Body panel overlays will be dynamically generated here -->
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Panel Assessment Form -->
        <div class="col-lg-6 mb-4">
            <div class="card shadow-sm">
                <div class="card-header" style="background-color: var(--primary-color); color: white;">
                    <h5 class="mb-0">Panel Assessment Details</h5>
                </div>
                <div class="card-body">
                    <form id="bodyPanelAssessmentForm">
                        @csrf
                        
                        <!-- Dynamic body panel assessments will be generated by JavaScript -->
                        <div id="bodyPanelAssessments">
                            <!-- Panel forms will be added here -->
                        </div>

                        <div class="mt-4 d-flex justify-content-between">
                            <button type="button" class="btn btn-outline-secondary" id="backBtn">
                                <i class="bi bi-arrow-left me-1"></i>Back to Visual Inspection
                            </button>
                            <div class="button-group-responsive">
                                <button type="button" class="btn btn-secondary me-2 mb-2" id="saveDraftBtn">Save Draft</button>
                                <button type="submit" class="btn btn-primary mb-2" id="nextBtn">
                                    Continue to Interior Assessment <i class="bi bi-arrow-right ms-1"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional-css')
<link rel="stylesheet" href="{{ asset('css/panel-cards.css') }}">
<style>
/* Body Panel container - responsive for tablet-first design */
.body-panel-container {
    position: relative;
    max-width: 1005px;
    width: 100%;
    margin: 0 auto;
    background-color: #f8f9fa;
    padding: 0;
    overflow: visible;
}

/* Base body panel image - fully responsive */
.base-body-panel {
    width: 100%;
    height: auto;
    display: block;
    max-width: 1005px;
}

/* Panel overlay styling */
.panel-overlay {
    cursor: pointer;
    transition: all 0.3s ease;
    opacity: 0;
    position: absolute !important;
}

/* Hover effects for panels */
.panel-overlay:hover {
    opacity: 0.7;
    filter: brightness(0) saturate(100%) invert(21%) sepia(100%) saturate(7463%) hue-rotate(358deg) brightness(105%) contrast(115%);
}

.panel-overlay.active {
    opacity: 0.7;
    filter: brightness(0) saturate(100%) invert(21%) sepia(100%) saturate(7463%) hue-rotate(358deg) brightness(105%) contrast(115%);
}

/* Button responsive layout for tablets */
@media (max-width: 768px) {
    .button-group-responsive {
        display: flex;
        flex-direction: column;
        align-items: stretch;
        gap: 5px;
    }
    
    .button-group-responsive .btn {
        width: 100%;
        margin-right: 0 !important;
    }
    
    .mt-4.d-flex.justify-content-between {
        flex-direction: column !important;
        gap: 10px;
    }
    
    #backBtn {
        width: 100%;
        margin-bottom: 5px;
    }
}

/* Ensure 5px margin bottom for Save Draft on all screen sizes */
#saveDraftBtn {
    margin-bottom: 5px !important;
}
</style>
@endsection

@section('additional-js')
<script src="{{ asset('js/inspection-cards.js') }}"></script>
<script>
// Function to load CSV data and generate panel overlays
async function loadBodyPanelData() {
    try {
        const response = await fetch('/panelimages.csv');
        const csvText = await response.text();
        
        // Parse CSV
        const lines = csvText.trim().split('\n');
        const headers = lines[0].split(',');
        const panels = [];
        
        for (let i = 1; i < lines.length; i++) {
            const values = lines[i].split(',');
            const panel = {};
            headers.forEach((header, index) => {
                panel[header] = values[index];
            });
            panels.push(panel);
        }
        
        return panels;
    } catch (error) {
        console.error('Error loading panel data:', error);
        return [];
    }
}

// Function to generate panel overlays from CSV data
function generatePanelOverlays(panels) {
    const container = document.querySelector('.body-panel-container');
    
    panels.forEach(panel => {
        const img = document.createElement('img');
        img.src = `/images/panels/${panel.image_file}`;
        img.className = 'panel-overlay';
        img.setAttribute('data-panel', panel.id);
        img.style.position = 'absolute';
        img.style.left = panel.position_left;
        img.style.top = panel.position_top;
        img.style.width = panel.width;
        img.style.height = panel.height;
        if (panel.z_index) {
            img.style.zIndex = panel.z_index;
        }
        img.title = panel.name;
        img.alt = panel.name;
        
        container.appendChild(img);
    });
}

// Function to convert CSV data to InspectionCards format
function convertToInspectionCardsFormat(panels) {
    return panels.map(panel => ({
        id: `body_panel_${panel.id.replace('-', '_')}`,
        category: panel.name,
        panelId: panel.id
    }));
}

document.addEventListener('DOMContentLoaded', async function() {
    // Load panel data from CSV
    const panelData = await loadBodyPanelData();
    
    if (panelData.length > 0) {
        // Generate panel overlays
        generatePanelOverlays(panelData);
        
        // Convert to InspectionCards format
        const inspectionItems = convertToInspectionCardsFormat(panelData);
        
        // Initialize the reusable InspectionCards system for body panel assessment
        InspectionCards.init({
            // Required Configuration
            formId: 'bodyPanelAssessmentForm',
            containerId: 'bodyPanelAssessments',
            storageKey: 'bodyPanelAssessmentData',
            
            // Body Panel specific configuration
            hasOverlays: true,
            overlaySelector: '.panel-overlay',
            
            // Body panel items data from CSV
            items: inspectionItems,
            
            // Custom field configuration
            fields: {
                condition: { 
                    enabled: true, 
                    label: 'Condition', 
                    options: ['Good', 'Average', 'Bad'] 
                },
                comments: { 
                    enabled: true, 
                    label: 'Comments', 
                    type: 'select',
                    options: ['Scratch', 'Dent', 'Scuffed', 'Chipmark', 'Paintwork', 'Structural damage'] 
                },
                additional_comments: { 
                    enabled: true, 
                    label: 'Additional Comments', 
                    type: 'text', 
                    placeholder: 'Additional comments' 
                }
            },
            
            // Callback for form submission
            onFormSubmit: function(data) {
                sessionStorage.setItem('bodyPanelAssessmentData', JSON.stringify(data));
                window.location.href = '/inspection/interior';
            }
        });
    }
    
    // Handle navigation buttons
    document.getElementById('backBtn').addEventListener('click', function() {
        if (confirm('Are you sure you want to go back? Any unsaved data will be lost.')) {
            window.location.href = '/inspection/visual';
        }
    });
    
    document.getElementById('saveDraftBtn').addEventListener('click', function() {
        InspectionCards.saveData();
        alert('Draft saved successfully!');
    });
    
    document.getElementById('nextBtn').addEventListener('click', function(e) {
        e.preventDefault(); // Prevent form submission
        InspectionCards.saveData();
        window.location.href = '/inspection/interior';
    });
});
</script>
@endsection