@extends('layouts.app')

@section('title', 'Tyres & Rims Assessment')

@section('content')
<div class="container-fluid px-4">
    <!-- Progress Breadcrumb -->
    <div class="row mb-3">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="/inspection/visual" style="color: var(--primary-color);">Visual Inspection</a></li>
                    <li class="breadcrumb-item"><a href="/inspection/body-panel" style="color: var(--primary-color);">Body Panel Assessment</a></li>
                    <li class="breadcrumb-item"><a href="/inspection/interior" style="color: var(--primary-color);">Interior Assessment</a></li>
                    <li class="breadcrumb-item"><a href="/inspection/service-booklet" style="color: var(--primary-color);">Service Booklet</a></li>
                    <li class="breadcrumb-item active" aria-current="page" style="color: var(--primary-color); font-weight: 600;">Tyres & Rims Assessment</li>
                    <li class="breadcrumb-item text-muted">Mechanical Report</li>
                </ol>
            </nav>
        </div>
    </div>

    <!-- Header -->
    <div class="text-center mb-4">
        <h1 class="display-5 text-gradient mb-2">ALPHA Inspection</h1>
        <h2 class="h4">Tyres & Rims Assessment</h2>
        <p class="text-muted">Document the condition and specifications of all four tyres and rims</p>
    </div>

    <!-- Tyres & Rims Assessment -->
    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-header" style="background-color: var(--primary-color); color: white;">
                    <h5 class="mb-0">Tyres & Rims:</h5>
                </div>
                <div class="card-body">
                    <form id="tyresRimsAssessmentForm">
                        @csrf
                        
                        
                        <!-- Dynamic tyre assessments will be generated by JavaScript -->
                        <div id="tyresRimsAssessments">
                            <!-- Tyre forms will be added here -->
                        </div>

                        <!-- Disclaimer Section -->
                        <div class="alert alert-info mt-4">
                            <p class="mb-2"><strong>Tyre Safety Information:</strong></p>
                            <p class="mb-2">It is recommended that tyres are replaced when the tread depth reaches 2mm. If uneven tyre wear is noted, this may indicate incorrect geometry, which can result in excessive and rapid tyre wear. A full steering and geometry check is therefore recommended.</p>
                            <p class="mb-2">If this vehicle is fitted with "Run Flat" tyres and no spare wheel. The tyre's effectiveness in a puncture situation cannot be commented on.</p>
                            <p class="mb-0">It is advised to have tyres of the correct size and of similar make, tread pattern and tread depth across axles. This will benefit steering and handling, the operation of the transmission, 4 wheel drive, traction control, ABS and puncture detection systems. This can also prevent premature transmission wear or failure.</p>
                        </div>

                        <!-- Action buttons -->
                        <div class="mt-4 d-flex justify-content-between">
                            <button type="button" class="btn btn-outline-secondary" id="backBtn">
                                <i class="bi bi-arrow-left me-1"></i>Back to Service Booklet
                            </button>
                            <div class="button-group-responsive">
                                <button type="button" class="btn btn-success me-2 mb-2" id="simplePreviewBtn">
                                    <i class="bi bi-eye me-1"></i>Simple Preview
                                </button>
                                <button type="button" class="btn btn-secondary me-2 mb-2" id="saveDraftBtn">Save Draft</button>
                                <button type="submit" class="btn btn-primary mb-2" id="nextBtn">
                                    Continue to Mechanical Report <i class="bi bi-arrow-right ms-1"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('additional-css')
<link rel="stylesheet" href="{{ asset('css/panel-cards.css') }}">
<style>
/* Tyres-specific styling - Card layout with labels above fields */
#tyresRimsAssessments .panel-controls {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr auto; /* 5 equal columns + photo button */
    gap: 10px;
    align-items: start;
}

#tyresRimsAssessments .form-field-group {
    display: flex;
    flex-direction: column;
}

#tyresRimsAssessments .field-label {
    font-size: 12px;
    font-weight: 600;
    color: var(--text-color);
    margin-bottom: 4px;
    text-align: center;
    background-color: #b8dae0;
    padding: 4px 8px;
    border-radius: 3px;
}

#tyresRimsAssessments .form-control {
    border: 1px solid #ccc;
    border-radius: 4px;
    padding: 6px 8px;
    text-align: center;
    font-size: 14px;
}

#tyresRimsAssessments .photo-btn {
    align-self: end;
    margin-bottom: 0;
}

@media (max-width: 768px) {
    #tyresRimsAssessments .panel-controls {
        grid-template-columns: 1fr;
        gap: 15px;
    }
    
    #tyresRimsAssessments .field-label {
        text-align: left;
    }
    
    #tyresRimsAssessments .form-control {
        text-align: left;
    }
}

/* Alert styling for disclaimer */
.alert-info {
    background-color: #e8f4f8;
    border-color: var(--primary-color);
    color: var(--text-color);
}

/* Button responsive layout for tablets */
@media (max-width: 768px) {
    .button-group-responsive {
        display: flex;
        flex-direction: column;
        align-items: stretch;
        gap: 5px;
    }
    
    .button-group-responsive .btn {
        width: 100%;
        margin-right: 0 !important;
    }
    
    .mt-4.d-flex.justify-content-between {
        flex-direction: column !important;
        gap: 10px;
    }
    
    #backBtn {
        width: 100%;
        margin-bottom: 5px;
    }
}

/* Ensure 5px margin bottom for Save Draft on all screen sizes */
#saveDraftBtn {
    margin-bottom: 5px !important;
}

/* Condition-based color coding for Overall Condition dropdowns */
select[name$="-condition"] {
    transition: background-color 0.3s ease;
}

select[name$="-condition"][value="good"] {
    background-color: #28a745 !important;
    color: white !important;
}

select[name$="-condition"][value="average"] {
    background-color: #ffc107 !important;
    color: #212529 !important;
}

select[name$="-condition"][value="poor"] {
    background-color: #dc3545 !important;
    color: white !important;
}
</style>
@endsection

@section('additional-js')
<script src="{{ asset('js/inspection-cards.js') }}"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Initialize the reusable InspectionCards system for tyres-rims assessment
    InspectionCards.init({
        // Required Configuration
        formId: 'tyresRimsAssessmentForm',
        containerId: 'tyresRimsAssessments',
        storageKey: 'tyresRimsAssessmentData',
        
        // Tyres-Rims specific configuration (no overlays)
        hasOverlays: false,
        
        // Tyre items data
        items: [
            { id: 'front_left', category: 'Front Left Tyre', panelId: 'front-left' },
            { id: 'front_right', category: 'Front Right Tyre', panelId: 'front-right' },
            { id: 'rear_left', category: 'Rear Left Tyre', panelId: 'rear-left' },
            { id: 'rear_right', category: 'Rear Right Tyre', panelId: 'rear-right' },
            { id: 'spare', category: 'Spare Tyre', panelId: 'spare' }
        ],
        
        // Custom field configuration for tyres (matching 3.png layout)
        fields: {
            size: { 
                enabled: true, 
                label: 'Size', 
                type: 'text', 
                placeholder: 'e.g., 225/45R/18' 
            },
            manufacture: { 
                enabled: true, 
                label: 'Manufacture', 
                type: 'text', 
                placeholder: 'e.g., Continental' 
            },
            model: { 
                enabled: true, 
                label: 'Model', 
                type: 'text', 
                placeholder: 'e.g., SportContact' 
            },
            tread_depth: { 
                enabled: true, 
                label: 'Tread Depth (mm)', 
                type: 'text', 
                placeholder: 'e.g., 5mm' 
            },
            damages: { 
                enabled: true, 
                label: 'Damages', 
                type: 'text', 
                placeholder: 'e.g., Uneven rundown' 
            }
        },
        
        // Callback for form submission
        onFormSubmit: function(data) {
            sessionStorage.setItem('tyresRimsAssessmentData', JSON.stringify(data));
            window.location.href = '/inspection/mechanical-report';
        }
    });
    
    // Handle navigation buttons
    document.getElementById('backBtn').addEventListener('click', function() {
        if (confirm('Are you sure you want to go back? Any unsaved data will be lost.')) {
            window.location.href = '/inspection/service-booklet';
        }
    });
    
    document.getElementById('saveDraftBtn').addEventListener('click', function() {
        InspectionCards.saveData();
        alert('Draft saved successfully!');
    });
    
    // Simple Preview button handler
    document.getElementById('simplePreviewBtn').addEventListener('click', function() {
        console.log('Tyres & Rims Simple Preview clicked');
        
        // Get form data directly from InspectionCards
        let formData = {};
        let imageData = {};
        
        try {
            if (window.InspectionCards && typeof InspectionCards.getFormData === 'function') {
                formData = InspectionCards.getFormData();
                imageData = InspectionCards.getImages();
                console.log('Tyres Preview - Form Data:', formData);
                console.log('Tyres Preview - Image Data:', imageData);
            }
        } catch (e) {
            console.error('Error getting data:', e);
        }
        
        // If no data from InspectionCards, try manual collection
        if (Object.keys(formData).length === 0) {
            const form = document.getElementById('tyresRimsAssessmentForm');
            if (form) {
                const formDataObj = new FormData(form);
                for (let [key, value] of formDataObj.entries()) {
                    if (value && key !== '_token') {
                        formData[key] = value;
                    }
                }
            }
        }
        
        if (Object.keys(formData).length === 0) {
            alert('No data to preview. Please fill out at least one tyre assessment.');
            return;
        }
        
        // Prepare data for preview
        const previewData = {
            data: formData,
            images: imageData
        };
        
        // Submit to preview endpoint
        fetch('/preview/tyres-rims', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
            },
            body: JSON.stringify(previewData)
        })
        .then(response => response.text())
        .then(html => {
            // Open preview in new window
            const previewWindow = window.open('', '_blank');
            previewWindow.document.write(html);
            previewWindow.document.close();
        })
        .catch(error => {
            console.error('Preview error:', error);
            alert('Error generating preview: ' + error.message);
        });
    });
    
    document.getElementById('nextBtn').addEventListener('click', function() {
        InspectionCards.saveData();
        window.location.href = '/inspection/mechanical-report';
    });
    
    // Add color coding for condition dropdowns
    document.addEventListener('change', function(e) {
        if (e.target.name && e.target.name.endsWith('-condition')) {
            const select = e.target;
            // Remove existing condition classes
            select.classList.remove('condition-good', 'condition-average', 'condition-poor');
            
            // Set the value attribute for CSS selector
            select.setAttribute('value', select.value);
            
            // Add appropriate condition class for additional styling if needed
            if (select.value) {
                select.classList.add(`condition-${select.value}`);
            }
        }
    });
});
</script>
@endsection