#!/usr/bin/expect -f

set timeout 30
spawn ssh -p 22000 alphains@alphainspections.co.za

expect "password:"
send "Suq8h0QkFB\[+18\r"

expect "$ "
send "cd /home/alphains/staging\r"

expect "$ "
send "git pull origin staging\r"

expect "$ "
send "php artisan config:clear\r"

expect "$ "
send "php artisan cache:clear\r"

expect "$ "
send "php artisan view:clear\r"

expect "$ "
send "php artisan route:clear\r"

expect "$ "
send "echo 'Deployment complete!'\r"

expect "$ "
send "exit\r"

expect eof