#!/bin/bash

echo "==========================================="
echo "Staging Server Deployment Script"
echo "==========================================="
echo ""
echo "Server: alphainspections.co.za"
echo "Port: 22000"
echo "User: alphains"
echo "Password: Suq8h0QkFB[+18"
echo ""
echo "Run these commands after connecting:"
echo ""
echo "cd /home/alphains/staging"
echo "git pull origin staging"
echo "php artisan config:clear"
echo "php artisan cache:clear"
echo "php artisan view:clear"
echo "php artisan route:clear"
echo ""
echo "Optional (if needed):"
echo "composer install --no-dev"
echo "php artisan migrate"
echo ""